<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Unable to login please refer the attached screenshot]]>
    </line>
    <line>
      <![CDATA[Unable to verify manager ID please refer the attached screenshot]]>
    </line>
  </reporter-output>
  <suite started-at="2022-03-14T14:10:55Z" name="Default suite" finished-at="2022-03-14T14:11:11Z" duration-ms="16294">
    <groups>
    </groups>
    <test started-at="2022-03-14T14:10:55Z" name="Default test" finished-at="2022-03-14T14:11:11Z" duration-ms="16294">
      <class name="com.masterPageUI.testCases.TC_SuccessfullUserLogin">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.masterPageUI.testCases.TC_SuccessfullUserLogin@38102d01]" started-at="2022-03-14T19:40:55Z" name="openBrowser" finished-at="2022-03-14T19:41:07Z" duration-ms="11902" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method signature="loginTest()[pri:0, instance:com.masterPageUI.testCases.TC_SuccessfullUserLogin@38102d01]" started-at="2022-03-14T19:41:07Z" name="loginTest" finished-at="2022-03-14T19:41:11Z" duration-ms="3743" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [/Gu33ru99 Bank Manager HomePage] but found [Guru99 Bank Manager HomePage]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [/Gu33ru99 Bank Manager HomePage] but found [Guru99 Bank Manager HomePage]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.masterPageUI.testCases.TC_SuccessfullUserLogin.loginTest(TC_SuccessfullUserLogin.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Unable to login please refer the attached screenshot]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="verifyusername()[pri:0, instance:com.masterPageUI.testCases.TC_SuccessfullUserLogin@38102d01]" started-at="2022-03-14T19:41:11Z" name="verifyusername" finished-at="2022-03-14T19:41:11Z" duration-ms="449" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Unable to verify manager ID please refer the attached screenshot]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyusername -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.masterPageUI.testCases.TC_SuccessfullUserLogin@38102d01]" started-at="2022-03-14T19:41:11Z" name="closeBrowser" finished-at="2022-03-14T19:41:11Z" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.masterPageUI.testCases.TC_SuccessfullUserLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
